# ci-templates.yml
stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://dind:2375
  DOCKER_TLS_CERTDIR: ""

.test-app-template:
  stage: test
  image: alpine
  tags:
    - k8s-gitlab-runner
  script:
    - echo "Running tests for $APP_NAME..."
    - sleep 10

.build-docker-image-template:
  stage: build
  tags:
    - k8s-gitlab-runner
  image: docker:latest
  services:
    - name: docker:dind-rootless
      alias: docker
      command:
        - --host=tcp://0.0.0.0:2375  # Explicitly expose the Docker daemon
        - --tls=false

  variables:
    DOCKER_HOST: tcp://docker:2375  # Point Docker CLI to the DinD service
    DOCKER_TLS_CERTDIR: ""         # Disable TLS for DinD
    DOCKER_BUILDKIT: 1             # Enable BuildKit for faster builds
  script:
    - sleep 10
    - echo "Pulling pre-built image (if exists) to use as cache..."
    - docker pull registry.fullstack.pw/$APP_NAME:latest || true
    - echo "Building Docker image for $APP_NAME..."
    - docker build --cache-from registry.fullstack.pw/$APP_NAME:latest -t registry.fullstack.pw/$APP_NAME:latest $DOCKER_BUILD_PATH
    - echo "Pushing Docker image to the registry..."
    - docker push registry.fullstack.pw/$APP_NAME:latest


.deploy-app-template:
  stage: deploy
  image: alpine
  tags:
    - k8s-gitlab-runner
  script:
    - apk update && apk add -y curl
    - echo "Deploying $APP_NAME to $ENVIRONMENT..."
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" > ~/.kube/config
    - |
      if [ -n "$CONTEXT" ]; then
        kubectl config use-context "$CONTEXT"
      fi
    - kubectl apply -k "$KUSTOMIZE_DIR"

  variables:
    KUBECONFIG_DIR: "/vault/secrets/github-runner"
  before_script:
    - export KUBECONFIG_CONTENT=$(cat $KUBECONFIG_DIR)
    - export KUBECONFIG=~/.kube/config

