# ci-templates.yml
stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://dind:2375
  DOCKER_TLS_CERTDIR: ""

.test-app-template:
  stage: test
  image: alpine
  tags:
    - k8s-gitlab-runner
  script:
    - echo "Running tests for $APP_NAME..."
    - sleep 10

.build-docker-image-template:
  stage: build
  tags:
    - k8s-gitlab-runner
  image: docker:latest
  services:
    - name: docker:dind-rootless
      alias: dind

  script:
    - echo "Building Docker image for $APP_NAME..."
    - sleep 30
    - docker build -t registry.fullstack.pw/$APP_NAME:latest $DOCKER_BUILD_PATH
    - docker push registry.fullstack.pw/$APP_NAME:latest

.deploy-app-template:
  stage: deploy
  image: alpine
  tags:
    - k8s-gitlab-runner
  script:
    - echo "Deploying $APP_NAME to $ENVIRONMENT..."
    - sleep 10
