name: Run Cypress Tests

on:
  workflow_call:
    inputs:
      env-vars:
        description: JSON string of additional environment variables
        required: false
        type: string
        default: "{}"

jobs:
  cypress-tests:
    runs-on: self-hosted
    container:
      image: cypress/included:latest
      options: --user node

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Configure environment variables
        id: set-env
        run: |
          # Parse the JSON string of env vars and prepare them for export
          ENV_JSON='${{ inputs.env-vars }}'
          echo "$ENV_JSON" > env_vars.json

          # Debug
          echo "Received environment variables:"
          cat env_vars.json

          # Add all custom env vars with CYPRESS_ prefix
          jq -r 'to_entries | .[] | "CYPRESS_\(.key)=\(.value)"' env_vars.json >> cypress.env

          # Debug
          echo "Final environment variables:"
          cat cypress.env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ inputs['app-url'] }}
          CYPRESS_INSTALL_BINARY: 0
        with:
          cache-key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
