name: Deploy Kustomize Workload

on:
  workflow_call:
    inputs:
      kustomize-dir:
        description: Path to the directory containing the Kustomize manifests
        required: true
        type: string
      context:
        description: Kubernetes context to use (optional)
        required: false
        type: string
        default: ""

jobs:
  deploy-kustomize:
    name: Deploy Kustomize Workload
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Kubernetes Context (if provided)
        if: ${{ inputs.context != '' }}
        run: |
          cp /etc/kubeconfig $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context ${{ inputs.context }}


      - name: Deploy Using Kubectl with Kustomize
        run: kubectl apply -k ${{ inputs.kustomize-dir }}
        env:
          KUBECONFIG: /etc/kubeconfig
