name: Deploy Kustomize Workload

on:
  workflow_call:
    inputs:
      kustomize-dir:
        description: Path to the directory containing the Kustomize manifests
        required: true
        type: string
      context:
        description: Kubernetes context to use (optional)
        required: false
        type: string
        default: ""
      app-name:
        description: Name of the application (used in the Kustomize manifest)
        required: true
        type: string

jobs:
  deploy-kustomize:
    name: Deploy Kustomize Workload
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Kubernetes Context (if provided)
        if: ${{ inputs.context != '' }}
        run: |
          cp /etc/kubeconfig $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context ${{ inputs.context }}

      - name: Build Kustomize Manifests with Updated Image
        id: build
        run: |
          kubectl kustomize ${{ inputs.kustomize-dir }} \
            | sed "s|latest|${{ github.sha }}|" \
            > manifest.yaml

      - name: Display Updated Manifest
        run: cat manifest.yaml

      - name: Deploy Using Kubectl
        run: kubectl apply -f manifest.yaml
        env:
          KUBECONFIG: /etc/kubeconfig
